name: Java CI with Maven and NonDex









on: [push, pull_request]







jobs:


 build:


   runs-on: ubuntu-latest







   steps:


   - uses: actions/checkout@v2







   - name: Set up JDK 8


     uses: actions/setup-java@v2


     with:


       java-version: '8'
       distribution: 'adopt'

   - name: Build without tests
     run: mvn -B package --file pom.xml -DskipTests


   - name: Run tests without NonDex
     run: mvn test

   - name: Run tests with NonDex
     run: mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex -DnondexRuns=15 -DnondexSeed=54321  -DnondexMode=FULL
